Vagrant.configure(2) do |config|
config.vm.box = "debian/jessie64"

# Begin Configuring
config.vm.define "lamp" do|lamp|

lamp.vm.hostname = "lamp" # Setting up hostname
lamp.vm.network "private_network", ip: "192.168.205.10" # Setting up machine's IP Address
lamp.vm.provision :shell, path: "script.sh" # Provisioning with script.sh
end

# End Configuring
end